# Generated by Django 5.2.5 on 2025-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('doctor', 'Doctor'), ('staff', 'Staff'), ('admin', 'Admin'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
