# Generated by Django 5.2.5 on 2025-09-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('defaultuser', 'Default User'), ('student', 'Student'), ('doctor', 'Doctor'), ('staff', 'Staff'), ('admin', 'Admin'), ('pending', 'Pending')], default='defaultuser', max_length=15),
        ),
    ]
