# Generated by Django 5.2.5 on 2025-09-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_create_ssoauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
