# Generated by Django 5.2.5 on 2025-09-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_soft_delete_fields'),
        ('accounts', '0006_ssostate'),
    ]

    operations = [
    ]
